name = "ITensorsGPU"
uuid = "1350a740-ff57-428a-94c6-e4ae4d7859c0"
authors = ["Katharine Hyatt"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
